version: '1' 
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch1
    environment:
      - cluster.name=home
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana
    environment :
      SERVER_NAME: 10.0.0.2
      ELASTICSEARCH_URL: http://10.0.0.2:9200
    ports:
      - 5601:5601
volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
